### PR TITLE
Implemented a Book search and sorted tables for bookstores

### PR DESCRIPTION
**Pull request by ryantordesillas**
Features added:
- Users can now search for books across different bookstores (Case Sensitive)
- When a user visits a bookstore they can sort the table in alphabetical order
- Fixed a bug in the Owner view where owners could not return to their bookstore list

Testing:
- Added a integration test for the Search functionality (SearchBooksIT.java)

Test Passed!
image

### CODE REVIEW

**Review by kamransagheir — APPROVED** [review]
Looks good!

**Review by jolartabungar — APPROVED** [review]
Looks great!

**Comment by ryantordesillas** [comment]
Merged in recent changes so that my changes can be merged in. 

The test still passes!

**Comment by Hussainalbaidhani** [comment]
neat

**Review by Hussainalbaidhani — COMMENTED** [review]
looks neat

**Pull request merged**
