### PR TITLE
Add new entities to CommandLineRunner w/ minor changes to sorting

### PR DESCRIPTION
**Pull request by ryantordesillas**
I just added a couple new entities to the application to showcase the sorting table better. I also redid the sorting using a new script.

Features: 
- New Books
- New Owner and User
- New Bookstore
- Updated sorting
- Updated table

Did not add any tests since I'm not adding new functionality, I am just adding new entities.

### CODE REVIEW

**Review by jolartabungar — APPROVED** [review]
Looks great!

**Comment by ryantordesillas** [comment]
Don't merge this in yet, I'll update this once [this pull request](https://github.com/GroupProjectSysc4806Team5/4806GroupProject/pull/75) goes in to prevent any merge conflicts

**Comment by ryantordesillas** [comment]
It's good to go now!

**Review by jolartabungar — APPROVED** [review]
Looks good

**Pull request merged**
